In [1]:
#in order to load the model..we have function called load_model( to load the save model)
from tensorflow.keras.models import load_model

In [2]:
model=load_model('bank_churn.h5')

In [3]:
model

In [4]:
#to load the scaler model
import joblib


In [9]:
import numpy as np

In [10]:
sc=joblib.load('bank_churn_scaler.pkl')

In [11]:
sc

StandardScaler()

In [12]:
np.set_printoptions(precision=2,suppress=True)

In [14]:
data=np.array([[   528.  ,     31.  ,      6.  , 102016.72,      2.  ,      0.  ,
             0.  ,  80181.12,      0.  ,      0.  ,      1.  ]])

In [15]:
data

array([[   528.  ,     31.  ,      6.  , 102016.72,      2.  ,      0.  ,
             0.  ,  80181.12,      0.  ,      0.  ,      1.  ]])

In [16]:
#before going for predictions please perform scaling

In [18]:
data=sc.transform(data)

In [21]:
data

array([[-1.28, -0.75,  0.35,  0.41,  0.81, -1.54, -1.03, -0.35, -0.58,
        -0.58,  0.91]])

In [20]:
y=model.predict(data)

In [30]:
y

array([[False]])